//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test.proto
namespace DS_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_RotateMessage")]
  public partial class p_RotateMessage : global::ProtoBuf.IExtensible
  {
    public p_RotateMessage() {}
    
    private float _delta_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"delta_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float delta_x
    {
      get { return _delta_x; }
      set { _delta_x = value; }
    }
    private float _delta_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"delta_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float delta_y
    {
      get { return _delta_y; }
      set { _delta_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_PositionMessage")]
  public partial class p_PositionMessage : global::ProtoBuf.IExtensible
  {
    public p_PositionMessage() {}
    
    private float _delta_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"delta_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float delta_x
    {
      get { return _delta_x; }
      set { _delta_x = value; }
    }
    private float _delta_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"delta_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float delta_y
    {
      get { return _delta_y; }
      set { _delta_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_SpawnMessage")]
  public partial class p_SpawnMessage : global::ProtoBuf.IExtensible
  {
    public p_SpawnMessage() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _position_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_x
    {
      get { return _position_x; }
      set { _position_x = value; }
    }
    private float _position_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_y
    {
      get { return _position_y; }
      set { _position_y = value; }
    }
    private float _position_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_z
    {
      get { return _position_z; }
      set { _position_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_InputMessage")]
  public partial class p_InputMessage : global::ProtoBuf.IExtensible
  {
    public p_InputMessage() {}
    
    private float _moving_x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"moving_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float moving_x
    {
      get { return _moving_x; }
      set { _moving_x = value; }
    }
    private float _moving_y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"moving_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float moving_y
    {
      get { return _moving_y; }
      set { _moving_y = value; }
    }
    private float _moving_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"moving_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float moving_z
    {
      get { return _moving_z; }
      set { _moving_z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_EnterAreaMessage")]
  public partial class p_EnterAreaMessage : global::ProtoBuf.IExtensible
  {
    public p_EnterAreaMessage() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _health;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int health
    {
      get { return _health; }
      set { _health = value; }
    }
    private float _position_x;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_x
    {
      get { return _position_x; }
      set { _position_x = value; }
    }
    private float _position_y;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_y
    {
      get { return _position_y; }
      set { _position_y = value; }
    }
    private float _position_z;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"position_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float position_z
    {
      get { return _position_z; }
      set { _position_z = value; }
    }
    private float _direction_x;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"direction_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction_x
    {
      get { return _direction_x; }
      set { _direction_x = value; }
    }
    private float _direction_y;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"direction_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction_y
    {
      get { return _direction_y; }
      set { _direction_y = value; }
    }
    private float _direction_z;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"direction_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float direction_z
    {
      get { return _direction_z; }
      set { _direction_z = value; }
    }
    private float _rotation_x;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"rotation_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_x
    {
      get { return _rotation_x; }
      set { _rotation_x = value; }
    }
    private float _rotation_y;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"rotation_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_y
    {
      get { return _rotation_y; }
      set { _rotation_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_LeaveAreaMessage")]
  public partial class p_LeaveAreaMessage : global::ProtoBuf.IExtensible
  {
    public p_LeaveAreaMessage() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_CustomSyncMsg")]
  public partial class p_CustomSyncMsg : global::ProtoBuf.IExtensible
  {
    public p_CustomSyncMsg() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _msg_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msg_type
    {
      get { return _msg_type; }
      set { _msg_type = value; }
    }
    private DS_protocol.p_InputMessage _Input = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Input", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_InputMessage Input
    {
      get { return _Input; }
      set { _Input = value; }
    }
    private DS_protocol.p_SpawnMessage _Spawn = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Spawn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_SpawnMessage Spawn
    {
      get { return _Spawn; }
      set { _Spawn = value; }
    }
    private DS_protocol.p_RotateMessage _Rotate = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Rotate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_RotateMessage Rotate
    {
      get { return _Rotate; }
      set { _Rotate = value; }
    }
    private DS_protocol.p_PositionMessage _Position = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_PositionMessage Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private DS_protocol.p_EnterAreaMessage _EnterArea = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"EnterArea", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_EnterAreaMessage EnterArea
    {
      get { return _EnterArea; }
      set { _EnterArea = value; }
    }
    private DS_protocol.p_LeaveAreaMessage _LeaveArea = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"LeaveArea", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_LeaveAreaMessage LeaveArea
    {
      get { return _LeaveArea; }
      set { _LeaveArea = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_Join")]
  public partial class p_Join : global::ProtoBuf.IExtensible
  {
    public p_Join() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_AskFrame")]
  public partial class p_AskFrame : global::ProtoBuf.IExtensible
  {
    public p_AskFrame() {}
    
    private readonly global::System.Collections.Generic.List<int> _areas = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> areas
    {
      get { return _areas; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _frames = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_StartGame")]
  public partial class p_StartGame : global::ProtoBuf.IExtensible
  {
    public p_StartGame() {}
    
    private int _test;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int test
    {
      get { return _test; }
      set { _test = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_Frame")]
  public partial class p_Frame : global::ProtoBuf.IExtensible
  {
    public p_Frame() {}
    
    private byte[] _buffers;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"buffers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] buffers
    {
      get { return _buffers; }
      set { _buffers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_SyncFrame")]
  public partial class p_SyncFrame : global::ProtoBuf.IExtensible
  {
    public p_SyncFrame() {}
    
    private int _frame_count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frame_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int frame_count
    {
      get { return _frame_count; }
      set { _frame_count = value; }
    }
    private readonly global::System.Collections.Generic.List<DS_protocol.p_CustomSyncMsg> _msg_list = new global::System.Collections.Generic.List<DS_protocol.p_CustomSyncMsg>();
    [global::ProtoBuf.ProtoMember(2, Name=@"msg_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DS_protocol.p_CustomSyncMsg> msg_list
    {
      get { return _msg_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_IdToFrames")]
  public partial class p_IdToFrames : global::ProtoBuf.IExtensible
  {
    public p_IdToFrames() {}
    
    private int _areaid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaid
    {
      get { return _areaid; }
      set { _areaid = value; }
    }
    private readonly global::System.Collections.Generic.List<DS_protocol.p_SyncFrame> _frames = new global::System.Collections.Generic.List<DS_protocol.p_SyncFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DS_protocol.p_SyncFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_ReplyJoin")]
  public partial class p_ReplyJoin : global::ProtoBuf.IExtensible
  {
    public p_ReplyJoin() {}
    
    private int _real_player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"real_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int real_player_id
    {
      get { return _real_player_id; }
      set { _real_player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_ReplyAskFrame")]
  public partial class p_ReplyAskFrame : global::ProtoBuf.IExtensible
  {
    public p_ReplyAskFrame() {}
    
    private readonly global::System.Collections.Generic.List<DS_protocol.p_IdToFrames> _areas_to_frames = new global::System.Collections.Generic.List<DS_protocol.p_IdToFrames>();
    [global::ProtoBuf.ProtoMember(1, Name=@"areas_to_frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<DS_protocol.p_IdToFrames> areas_to_frames
    {
      get { return _areas_to_frames; }
    }
  
    private byte[] _buffers;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"buffers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] buffers
    {
      get { return _buffers; }
      set { _buffers = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_ReplyStart")]
  public partial class p_ReplyStart : global::ProtoBuf.IExtensible
  {
    public p_ReplyStart() {}
    
    private bool _start;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool start
    {
      get { return _start; }
      set { _start = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"p_AllMsg")]
  public partial class p_AllMsg : global::ProtoBuf.IExtensible
  {
    public p_AllMsg() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private DS_protocol.p_SyncFrame _SyncFrameMsg = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SyncFrameMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_SyncFrame SyncFrameMsg
    {
      get { return _SyncFrameMsg; }
      set { _SyncFrameMsg = value; }
    }
    private DS_protocol.p_Join _Join = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Join", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_Join Join
    {
      get { return _Join; }
      set { _Join = value; }
    }
    private DS_protocol.p_AskFrame _AskFrame = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"AskFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_AskFrame AskFrame
    {
      get { return _AskFrame; }
      set { _AskFrame = value; }
    }
    private DS_protocol.p_StartGame _StartGame = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"StartGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_StartGame StartGame
    {
      get { return _StartGame; }
      set { _StartGame = value; }
    }
    private DS_protocol.p_Frame _Frame = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Frame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_Frame Frame
    {
      get { return _Frame; }
      set { _Frame = value; }
    }
    private DS_protocol.p_ReplyJoin _ReplyJoin = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ReplyJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_ReplyJoin ReplyJoin
    {
      get { return _ReplyJoin; }
      set { _ReplyJoin = value; }
    }
    private DS_protocol.p_ReplyAskFrame _ReplyAskFrame = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ReplyAskFrame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_ReplyAskFrame ReplyAskFrame
    {
      get { return _ReplyAskFrame; }
      set { _ReplyAskFrame = value; }
    }
    private DS_protocol.p_ReplyStart _ReplyStart = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ReplyStart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DS_protocol.p_ReplyStart ReplyStart
    {
      get { return _ReplyStart; }
      set { _ReplyStart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}